package org.example.backend.utils.enums;

public enum CandidateStatus {
    OPEN, BANNED, WAITING_FOR_INTERVIEW, CANCELLED_INTERVIEW,
    PASSED_INTERVIEW, FAILED_INTERVIEW, WAITING_FOR_APPROVAL,
    APPROVE_OFFER, REJECT_OFFER, WAITING_FOR_RESPONSE,
    ACCEPTED_OFFER, DECLINED_OFFER, CANCELLED_OFFER
}
